- hosts: webserver
  become: yes
  become_user: root
  vars_files: 
      -  "{{ ansible_facts['distribution'] }}-{{ ansible_facts['distribution_version']}}.yml"
  tasks:
  - service:
          name: "{{ service_name }}"
          state: stopped
    ignore_errors: yes
  - package:
          name: "{{ pkg_name}}"
          state: absent
  - file: 
          dest: "/var/www"
          state: absent
