- hosts: webserver
  become: yes
  become_user: root
  vars_files: 
      -  "{{ ansible_facts['distribution'] }}-{{ ansible_facts['distribution_version']}}.yml"
  tasks:
  - package:
          name: "{{ pkg_name}}"
          #when: os_name == "Redhat:8.0"
  - copy: 
          dest: "/var/www/html/index.html"
          content: "here we go"
  - service:
          name: "{{ service_name }}"
          state: started
